[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  port = 9999
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
